apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-upload-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-upload-minio
  template:
    metadata:
      labels:
        app: music-upload-minio
    spec:
      containers:
        - name: music-upload-minio
          image: quay.io/minio/minio
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: minio99
            - name: MINIO_ROOT_PASSWORD
              value: minio123
          volumeMounts:
            - mountPath: /data
              name: music-upload-minio-storage
      volumes:
        - name: music-upload-minio-storage
          persistentVolumeClaim:
            claimName: music-upload-minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: music-upload-minio-service
spec:
  selector:
    app: music-upload-minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-upload-minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi