apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-upload-recommendation-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: music-upload-recommendation-engine
  template:
    metadata:
      labels:
        app: music-upload-recommendation-engine
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -z music-upload-mysql-db-service 3306; do echo waiting; sleep 2; done;' ]
      containers:
        - name: music-upload-recommendation-engine
          image: kovacsbotondjanos/musicupload-recommendation-engine:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://music-upload-mysql-db-service:3306/music?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: ASD123
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: music-upload-recommendation-engine-service
spec:
  selector:
    app: music-upload-recommendation-engine
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
