apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-upload-recommendation-engine
spec:
  selector:
    matchLabels:
      app: music-upload-recommendation-engine
  template:
    metadata:
      labels:
        app: music-upload-recommendation-engine
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -z music-upload-mysql-db-service 3306; do echo waiting; sleep 2; done;' ]
      containers:
        - name: music-upload-recommendation-engine
          image: kovacsbotondjanos/musicupload-recommendation-engine:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://music-upload-mysql-db-service:3306/music?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: ASD123
          resources:
            requests:
              memory: "800Mi"
              cpu: "750m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: music-upload-recommendation-engine-service
spec:
  selector:
    app: music-upload-recommendation-engine
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: music-upload-recommendation-engine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: music-upload-recommendation-engine
  minReplicas: 1
  maxReplicas: 2
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
